service: countyapi
provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 30
package:
  include:
    - ./data/**/**/*
functions:
  county:
    handler: handler.county
    events:
      - http:
          path: api/{state}/county/boundary
          method: get
